In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.float_format', '{:.2f}'.format)

In [48]:
dados='CARAMELO.csv'
df=pd.read_csv(dados , encoding='utf-8', sep=';')

df.head(10) 
#10 primeiras linhas

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,2024-12-20,2024-12-30,Pix,Drone,"8979,56"
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,2023-11-22,2023-11-28,Dinheiro,Celular,"112146,00"
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,2023-08-25,2023-08-27,Dinheiro,Suco,"37,08"
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,2024-08-03,2024-08-04,Dinheiro,Notebook,"13455,14"
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,2023-02-28,2023-03-08,Pix,Refrigerante,"17,33"
5,100010,Melo,49,BA,Salvador,Sr. Rhavi Siqueira,237,Feminino,55,BA,Salvador,183,Alimentos,Barilla,2023-04-13,2023-04-14,Pix,Macarrão,"20,33"
6,100011,Machado,40,RS,Caxias do Sul,Isaque Pimenta,25565,Masculino,67,RJ,Rio de Janeiro,283,Alimentos,Del Valle,2025-11-15,2025-11-25,Cartão,Suco,"29,87"
7,100012,Moreira,53,RJ,Rio de Janeiro,Sr. Gustavo Cavalcanti,27717,Masculino,62,BA,Salvador,286,Livros,Amazon,2025-07-07,2025-07-09,Cartão,A Revolução dos Bichos,"157,62"
8,100014,Moreira,53,RJ,Rio de Janeiro,Dr. Bruno Nunes,37283,Feminino,59,SP,Santos,615,Eletrônicos,Sony,2025-06-08,2025-06-10,Pix,Monitor,"15428,64"
9,100015,Teixeira,49,RS,Novo Hamburgo,Henry Gabriel Vasconcelos,36864,Masculino,60,RJ,Rio de Janeiro,926,Alimentos,Nestlé,2023-06-10,2023-06-12,Cartão,Chocolate,"25,67"

# Limpeza

In [49]:
df.isnull().sum()
#Quantidade de valores nulos por coluna

ID Venda               0
Loja                   0
ID Loja                0
Estado Loja            0
Cidade Loja            0
Nome Cliente           0
ID Cliente             0
Sexo                   0
Idade                  0
Estado Cliente         0
Cidade Cliente         0
ID Produto             0
Categoria Produto      0
Marca                  0
Data da Compra         0
Data da Entrega        0
Metodo de Pagamento    0
Produto                0
Valor de Venda         0
dtype: int64

In [50]:
df.info()
# Data de compra e entrega está como string e valor de venda também

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID Venda             150000 non-null  int64
 1   Loja                 150000 non-null  str
 2   ID Loja              150000 non-null  int64
 3   Estado Loja          150000 non-null  str
 4   Cidade Loja          150000 non-null  str
 5   Nome Cliente         150000 non-null  str
 6   ID Cliente           150000 non-null  int64
 7   Sexo                 150000 non-null  str
 8   Idade                150000 non-null  int64
 9   Estado Cliente       150000 non-null  str
 10  Cidade Cliente       150000 non-null  str
 11  ID Produto           150000 non-null  int64
 12  Categoria Produto    150000 non-null  str
 13  Marca                150000 non-null  str
 14  Data da Compra       150000 non-null  str
 15  Data da Entrega      150000 non-null  str
 16  Metodo de Pagamento  150000 non-null  str
 17  Produto              150000 non-null  str
 18  Valor de Venda       150000 non-null  str
dtypes: int64(5), str(14)
memory usage: 21.7 MB

In [51]:
df['Data da Compra'] = pd.to_datetime(df['Data da Compra'])
df['Data da Entrega'] = pd.to_datetime(df['Data da Entrega'])
df['Valor de Venda'] = pd.to_numeric(
    df['Valor de Venda']
        .astype(str)
        .str.replace('.', '', regex=False)
        .str.replace(',', '.', regex=False),
    errors='coerce'
)
#pd.to_datetime tranforma as colunas em datas
#pd.to_numeric converte para número , o primeiro replace remove os pontos e o segundo substitui vírgula por ponto
#erros='coerse' substitui valores caso existissem por 'NaN' 


df

,ID Venda,Loja,ID Loja,Estado Loja,Cidade Loja,Nome Cliente,ID Cliente,Sexo,Idade,Estado Cliente,Cidade Cliente,ID Produto,Categoria Produto,Marca,Data da Compra,Data da Entrega,Metodo de Pagamento,Produto,Valor de Venda
0,1,Melo,49,BA,Salvador,Lucas Silveira,35727,Masculino,24,BA,Vitória da Conquista,946,Eletrônicos,Lenovo,2024-12-20,2024-12-30,Pix,Drone,8979.56
1,10,Mendonça Machado Ltda.,7,SP,Sorocaba,Isabella Campos,2188,Feminino,41,MG,Uberlândia,112,Eletrônicos,Apple,2023-11-22,2023-11-28,Dinheiro,Celular,112146.00
2,1000,Cunha Mendes S.A.,97,BA,Camaçari,Marcela Barbosa,2293,Feminino,47,SP,Sorocaba,283,Alimentos,Del Valle,2023-08-25,2023-08-27,Dinheiro,Suco,37.08
3,100001,Nunes,77,MG,Contagem,Ravy Cunha,38559,Feminino,59,RJ,Petrópolis,805,Eletrônicos,Dell,2024-08-03,2024-08-04,Dinheiro,Notebook,13455.14
4,100007,Cunha Mendes S.A.,97,BA,Camaçari,Sra. Ana Cecília Pinto,19274,Masculino,27,SP,São Paulo,362,Alimentos,Coca-Cola,2023-02-28,2023-03-08,Pix,Refrigerante,17.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,99992,Barbosa,96,RS,Pelotas,Caleb da Mota,223,Masculino,63,BA,Salvador,623,Alimentos,Pilão,2024-11-11,2024-11-15,Cartão,Café,33.27
149996,99994,Aparecida da Conceição e Filhos,15,RJ,Campos dos Goytacazes,Eduardo Cavalcanti,8975,Masculino,39,BA,Salvador,253,Alimentos,Vigorelli,2025-01-11,2025-01-13,Pix,Feijão,15.50
149997,99997,Moreira,53,RJ,Rio de Janeiro,Pedro Miguel Mendes,36587,Masculino,43,RS,Pelotas,535,Alimentos,Camil,2023-09-09,2023-09-15,Dinheiro,Arroz,27.83
149998,99998,Andrade,94,SP,Santos,Ana Luiza Porto,3938,Feminino,36,BA,Feira de Santana,183,Alimentos,Barilla,2025-01-01,2025-01-02,Pix,Macarrão,61.16
149999,99999,Teixeira,49,RS,Novo Hamburgo,Joana Moreira,11328,Feminino,24,BA,Feira de Santana,434,Roupas,Hering,2023-09-05,2023-09-10,Cartão,Camiseta,182.74

# Análise

In [52]:
df.columns

Index(['ID Venda', 'Loja', 'ID Loja', 'Estado Loja', 'Cidade Loja',
       'Nome Cliente', 'ID Cliente', 'Sexo', 'Idade', 'Estado Cliente',
       'Cidade Cliente', 'ID Produto', 'Categoria Produto', 'Marca',
       'Data da Compra', 'Data da Entrega', 'Metodo de Pagamento', 'Produto',
       'Valor de Venda'],
      dtype='str')

In [58]:
#Valor de venda por loja 

df_venda_loja=df.groupby('Loja')['Valor de Venda'].sum().reset_index()
df_venda_loja

                               Loja  Valor de Venda
0                           Andrade     36868599.90
1   Aparecida da Conceição e Filhos     17209636.57
2                           Barbosa     15571997.27
3                             Cunha     36133723.77
4                  Cunha Gomes - EI     15287724.29
5                 Cunha Mendes S.A.     16004067.45
6                         Fernandes     37107099.24
7                             Gomes     39371215.05
8                           Machado     15438498.57
9                              Melo     14618426.65
10           Mendonça Machado Ltda.     73919670.56
11                          Moreira     26847044.73
12                       Moura - ME     35509673.51
13                            Nunes     15711971.31
14            Ribeiro Sampaio Ltda.     15053199.25
15              Sampaio Viana Ltda.     18017479.95
16                           Santos     15090433.84
17                            Sousa     18350601.22
18                         Teixeira     15717865.33
19                           Vargas     17769332.66

In [61]:
#Valor de Venda por Categoria

df_categoria=df.groupby('Categoria Produto')['Valor de Venda'].sum().reset_index()
df_categoria.sort_values(by='Valor de Venda', ascending=False)

  Categoria Produto  Valor de Venda
1       Eletrônicos    398284376.66
3            Móveis     78552157.79
4            Roupas     14495598.61
0         Alimentos      2892560.74
2            Livros      1373567.32